# -*- coding: utf-8 -*-
"""titanic_exploratory_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IXLovhyr8zaoAbMnjbeo9jtyA3aGybyx
"""

import pandas as pd
df = pd.read_csv('train.csv')
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df

df.tail()

num_males = (df['Sex'] == 'male').sum()
print(num_males)

num_females = (df['Sex'] == 'female').sum()
print(num_females)

gender_count = df['Sex'].value_counts()
print(gender_count)

import matplotlib.pyplot as plt

gender_counts = {'Male': 577, 'Female': 314}

# Create a pie chart
plt.figure(figsize=(5, 5))
plt.pie(gender_counts.values(), labels=gender_counts.keys(), autopct='%1.1f%%', startangle=140)
plt.title('Gender Distribution on the Ship')
plt.axis('equal')
plt.show()

import pandas as pd
df = pd.read_csv('train.csv')
total_nan_values = df.isna().sum().sum()
print(total_nan_values)

nan_counts = df.isna().sum()
print(nan_counts)

columns_with_nan = df.columns[df.isna().any()].tolist()
print(columns_with_nan)



