# -*- coding: utf-8 -*-
"""titanic_regression_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lFPmotR2RmXJPsr0i9pRWCzjQFhpHYPr
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import accuracy_score, mean_squared_error, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

# Load the dataset
df = pd.read_csv('titanic.csv')

# Selecting features
features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']
X = df[features]
y = df['Survived']

# Preprocessing for numerical data
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

# Preprocessing for categorical data
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Bundle preprocessing for numerical and categorical data
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, ['Age', 'SibSp', 'Parch', 'Fare']),
        ('cat', categorical_transformer, ['Pclass', 'Sex', 'Embarked'])
    ])

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Logistic Regression pipeline
lr_pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                              ('classifier', LogisticRegression(random_state=42))])

# Train the Logistic Regression model
lr_pipeline.fit(X_train, y_train)

# Create a Linear Regression pipeline (note: we need to convert probabilities to 0/1 labels later)
linreg_pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                                  ('regressor', LinearRegression())])

# Train the Linear Regression model
linreg_pipeline.fit(X_train, y_train)

# Predicting with Logistic Regression
lr_predictions = lr_pipeline.predict(X_test)

# Evaluate Logistic Regression
print("Logistic Regression Classification Report:")
print(classification_report(y_test, lr_predictions))

# Predicting with Linear Regression and converting probabilities to binary outcomes
linreg_predictions = linreg_pipeline.predict(X_test)
linreg_predictions = np.where(linreg_predictions >= 0.5, 1, 0)

# Evaluate Linear Regression
print("Linear Regression as Classifier Report:")
print(classification_report(y_test, linreg_predictions))

